# Generated by Django 4.2 on 2025-03-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_transaction_narration_transaction_recipient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="unique_account_number",
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
