# Generated by Django 4.2 on 2025-03-10 19:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_userprofile_unique_account_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_activated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="apexfin_coins",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
    ]
