# Generated by Django 4.2 on 2025-04-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="debit_transaction_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
