# Generated by Django 4.2 on 2025-03-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_userprofile_is_activated_alter_transaction_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="cooldown_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
