# Generated by Django 4.2 on 2025-03-16 02:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_userprofile_cooldown_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="investment_profit",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
    ]
