# Generated by Django 4.2 on 2025-04-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("country", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField()),
            ],
        ),
    ]
